# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('tel_fixo', models.CharField(max_length=12)),
                ('cel', models.CharField(max_length=13)),
            ],
        ),
    ]
